### ISSUE TITLE
beautiful module 

### ISSUE THREAD

**Issue by Hamood111** [Kslpix/DarkMode_Evolution#16]
Hi I tried this module before but unfortunately it's not supposed any of global apps, but on EU custom rom the dark mode including all apps like social media ones and other more u can put it on dark mode I hope u bring the same EU rom feature or maybe it's work but not on my root I hope to upgrade it to become supporting kernelsu

**Comment by Kslpix** [comment]
Thank you for using my module! Unfortunately, I don't have a foreign version of my Xiaomi phone, so I can't fit it. If you have time, you can try to adapt, please understand the inconvenience.

**Comment by Hamood111** [comment]
> Thank you for using my module! Unfortunately, I don't have a foreign version of my Xiaomi phone, so I can't fit it. If you have time, you can try to adapt, please understand the inconvenience.

thanks for answer me back
